import JSZip from "jszip";
import { TransformedPackage } from "./transformer";

export async function createExportZip(pkg: TransformedPackage): Promise<Buffer> {
  const zip = new JSZip();

  // Root files
  zip.file("styles.css", pkg.css);
  zip.file("tokens.json", JSON.stringify(pkg.tokens, null, 2));
  zip.file("tailwind.config.js", pkg.tailwindConfig);
  zip.file("index.html", pkg.htmlPreview);
  zip.file("HeroComponent.tsx", pkg.componentCode);

  // Documentation / instructions
  const readme = `# StyleShift Package: ${pkg.preset.name}
Generated by StyleShift: Bridging Versions with Custom Web Aesthetics

Target Website: ${pkg.tokens.targetUrl}
Theme: ${pkg.preset.name} (${pkg.preset.color})

## Contents of this package
1. \`styles.css\` - Custom aesthetic stylesheet with variables, modern cards, and neon glow effects.
2. \`tokens.json\` - Design tokens (colors, typography scales, effect values).
3. \`tailwind.config.js\` - Ready-to-use Tailwind CSS configuration extension.
4. \`index.html\` - Standalone responsive preview of the transformed layout.
5. \`HeroComponent.tsx\` - React component ready to import into your Next.js or React application.

## How to use
- **Plain HTML/CSS**: Include \`<link rel="stylesheet" href="styles.css">\` in your HTML header.
- **Tailwind CSS**: Copy the theme extension from \`tailwind.config.js\` into your project's configuration.
- **Next.js / React**: Import \`HeroComponent.tsx\` into your pages.
`;

  zip.file("README.md", readme);

  const buffer = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 9 },
  });

  return buffer;
}
